### ISSUE TITLE
WEB-18 Crear view para fases

### ISSUE THREAD

**Issue by matias-fare** [JHeisecke/project-traceability-web#38]
proyectos --> fases --> tareas

**Comment by JHeisecke** [comment]
Será que podes arreglar de paso el color en el estado del proyecto, que sale así
![imagen](https://user-images.githubusercontent.com/34453933/91627515-efb8a880-e985-11ea-9c2c-af9633354306.png)
Debería salir así
![imagen](https://user-images.githubusercontent.com/34453933/91627523-f9daa700-e985-11ea-9d53-0b3ce4c5b49d.png)
En mi rama funciona en la pestaña de linea bases WEB-16
