### ISSUE TITLE
WEB-04 - Crear pantalla para Dashboard general

### ISSUE THREAD

**Issue by jazvillagra** [JHeisecke/project-traceability-web#5]
En el dashboard se debe tener:

1. Una cabecera con el boton de Logout
2. Un Burger button para desplegar las opciones disponibles
3. Un panel con el listado de proyectos, en cada uno de los proyectos se debe poder visualizar:
    -  Nombre del proyecto
    -  Estado del proyecto
    -  Botón para Ir al dashboard del proyecto
    -  Botón para Editar el proyecto
    -  Botón para Ver Usuarios del proyecto

**Comment by matias-fare** [comment]
Excelente @JHeisecke..

Pero no estoy pudiendo identificar donde se encuentras los siguientes puntos..

* Botón para Ir al dashboard del proyecto
* Botón para Editar el proyecto
* Botón para Ver Usuarios del proyecto

deberian estar en la compo acciones de cada proyecto?

**Comment by JHeisecke** [comment]
Gracias @matiasfare 
Eso es porque todavía no termine el issue
Saludos.-
